using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using SimplyBudget.Services;

namespace SimplyBudget.Models.Factories
{
    /// <summary>
    /// Reponsible for creating new Record instances.
    /// </summary>
    public class RecordFactory
    {
        /// <summary>
        /// Returns a new record with a unique ID generated by AppSettings.
        /// </summary>
        public static Record Create(RecordType type, decimal amount, DateTime date, string category, string description)
        {
            int id = AppSettings.Instance.GetNextID();
            return new Record(id, amount, date, category, description, type);
        }
    }
}
